packages:
  - apps/*
  - libs/*
  - docs/*

catalog:
  '@eslint/eslintrc': ~3.3.3
  '@mocks-server/main': ~4.1.0
  '@next/env': ~15.5.12
  '@tailwindcss/postcss': ~4.1.18
  '@testing-library/jest-dom': ~6.8.0
  '@testing-library/react': ~16.3.2
  '@types/jest': ~30.0.0
  '@types/node': ~24.3.3
  '@types/react': ~19.1.17
  '@types/react-dom': ~19.1.11
  autoprefixer: ~10.4.24
  connect-livereload: ~0.6.1
  eslint: ~9.34.0
  eslint-config-next: ~15.5.12
  express: ~5.1.0
  generate-react-cli: ~8.4.9
  jest: ~30.1.3
  jest-environment-jsdom: ~30.1.2
  livereload: ~0.10.3
  motion: ~12.23.12
  next: ~15.5.2
  nodemon: ~3.1.11
  postcss: ~8.5.6
  postcss-cli: ~11.0.1
  react: ~19.1.5
  react-dom: ~19.1.5
  swagger-ui-express: ~5.0.1
  tailwindcss: ~4.1.18
  ts-jest: ~29.4.6
  typescript: ~5.9.3
  yamljs: ~0.3.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - sharp
  - sqlite3
  - unrs-resolver
