FROM archlinux:latest

ENV NODE_MAJOR_VERSION=24
ENV PNPM_VERSION=10
ENV NODE_OPTIONS='--max-old-space-size=200'

WORKDIR /install
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm bash
RUN pacman -S --noconfirm git
RUN pacman -S --noconfirm curl
RUN pacman -S --noconfirm wget
RUN pacman -S --noconfirm unzip
RUN pacman -S --noconfirm zip
RUN pacman -S --noconfirm sudo

# Install Node and PNPM
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh -o get_nvm.sh
RUN bash get_nvm.sh
RUN bash -c "source $HOME/.bashrc && nvm install 24" 
RUN bash -c "source $HOME/.bashrc && nvm use 24"
RUN bash -c "source $HOME/.bashrc && nvm alias default 24"
RUN bash -c "source $HOME/.bashrc && corepack enable pnpm "
RUN bash -c "source $HOME/.bashrc && corepack use pnpm@10"
RUN bash -c "source $HOME/.bashrc && npm install -g bun"
RUN bash -c "source $HOME/.bashrc && bunx --bun pnpm i"

WORKDIR /app
COPY . .

# Install dependencies
RUN pnpm install --frozen-lockfile
# RUN pnpm run build

CMD ["bun", "td1/index.js"]